apiVersion: v1
kind: Namespace
metadata:
  name: code-server-demyxwp
---
apiVersion: v1
kind: Service
metadata:
  name: code-server-demyxwp
  namespace: code-server-demyxwp
spec:
  ports:
    - port: 8080
      name: https
      protocol: TCP
  selector:
    app: code-server-demyxwp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server-demyxwp
  name: code-server-demyxwp
  namespace: code-server-demyxwp
spec:
  selector:
    matchLabels:
      app: code-server-demyxwp
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server-demyxwp
    spec:
      containers:
        - env:
          - name: CODER_AUTH
            value: "false"
          image: demyx/code-server:wp
          imagePullPolicy: Always
          name: code-server-demyxwp
          ports:
            - containerPort: 8080
              name: https
