apiVersion: v1
kind: Namespace
metadata:
  name: code-server-demyxsage
---
apiVersion: v1
kind: Service
metadata:
  name: code-server-demyxsage
  namespace: code-server-demyxsage
spec:
  ports:
    - port: 3000
      name: https
      protocol: TCP
  selector:
    app: code-server-demyxsage
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server-demyxsage
  name: code-server-demyxsage
  namespace: code-server-demyxsage
spec:
  selector:
    matchLabels:
      app: code-server-demyxsage
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server-demyxsage
    spec:
      containers:
        - env:
          - name: CODER_AUTH
            value: "false"
          image: demyx/code-server:sage
          imagePullPolicy: Always
          name: code-server-demyxsage
          ports:
            - containerPort: 3000
              name: https
