apiVersion: v1
kind: Namespace
metadata:
  name: code-server-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: code-server-alpine
  namespace: code-server-alpine
spec:
  ports:
    - port: 8080
      name: https
      protocol: TCP
  selector:
    app: code-server-alpine
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server-alpine
  name: code-server-alpine
  namespace: code-server-alpine
spec:
  selector:
    matchLabels:
      app: code-server-alpine
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server-alpine
    spec:
      containers:
        - image: demyx/code-server:latest
          imagePullPolicy: Always
          name: code-server-alpine
          ports:
            - containerPort: 8080
              name: https
