apiVersion: v1
kind: Namespace
metadata:
  name: theia
---
apiVersion: v1
kind: Service
metadata:
  name: theia
  namespace: theia
spec:
  ports:
    - port: 3000
      name: https
      protocol: TCP
  selector:
    app: theia
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: theia
  name: theia
  namespace: theia
spec:
  selector:
    matchLabels:
      app: theia
  replicas: 1
  template:
    metadata:
      labels:
        app: theia
    spec:
      containers:
        - image: theiaide/theia:next
          imagePullPolicy: Always
          name: theia
          ports:
            - containerPort: 3000
              name: https
